/// Generated by AssetsRefGenerator on 2021/08/22
class Res {
  static const String africa = "assets/images/africa.png";
  static const String asia = "assets/images/asia.png";
  static const String australia = "assets/images/australia.png";
  static const String download = "assets/images/download.csv";
  static const String europe = "assets/images/europe.png";
  static const String ic_home_selected = "assets/images/ic_home_selected.svg";
  static const String ic_home_unselected = "assets/images/ic_home_unselected.svg";
  static const String ic_news_selected = "assets/images/ic_news_selected.svg";
  static const String ic_news_unselected = "assets/images/ic_news_unselected.svg";
  static const String ic_rank_selected = "assets/images/ic_rank_selected.svg";
  static const String ic_rank_unselected = "assets/images/ic_rank_unselected.svg";
  static const String ic_settings_selected = "assets/images/ic_settings_selected.svg";
  static const String ic_settings_unselected = "assets/images/ic_settings_unselected.svg";
  static const String north_america = "assets/images/north_america.png";
  static const String south_america = "assets/images/south_america.png";
  static const String countries = "assets/json/countries.json";
}
